/**
 * Settings Store
 * Manages theme (darkMode), language, and translations.
 */
import { writable, derived } from 'svelte/store';

// Theme state
export const darkMode = writable(false);

// Language state (default: English)
export const language = writable('en');

// Translations dictionary
const translations = {
    en: {
        gli: "Sum of 15 major central bank balance sheets in USD. ↑ Expansion = Liquidity injection (bullish) | ↓ Contraction = QT (bearish)",
        gli_cb: "Individual central bank assets in USD. Larger = more weight in global liquidity.",
        btc_fair: "BTC fair value derived from macro liquidity factors. Price above = overvalued, below = undervalued.",
        btc_bands: "±1σ/2σ bands show historical deviation range. Mean-reverts over time.",
        net_liq: "Fed Balance Sheet minus TGA and RRP. Key driver of US dollar liquidity.",
        rrp: "Reverse Repo drains liquidity from the system. ↓ RRP = Liquidity release (bullish)",
        tga: "Treasury General Account. ↓ TGA = Treasury spending = Liquidity injection",
        m2_global: "Global money supply in USD. Leading indicator for asset prices (45-90 day lag).",
        m2_country: "Country M2 money supply in local currency converted to USD.",
        cli: "Aggregates credit conditions, volatility, and lending. ↑ CLI = Easier credit (bullish) | ↓ Contraction = Tighter (bearish)",
        hy_spread: "High Yield bond spreads vs Treasuries. ↓ Spread = Risk-on (bullish) | ↑ Spread = Risk-off",
        ig_spread: "Investment Grade spreads. ↓ Spread = Credit easing | ↑ Spread = Credit stress",
        nfci_credit: "Fed's NFCI Credit subindex. ↓ Below 0 = Loose conditions | ↑ Above 0 = Tight",
        nfci_risk: "Fed's NFCI Risk subindex. ↓ Below 0 = Low fear | ↑ Above 0 = Elevated fear",
        lending: "Senior Loan Officer Survey. ↑ Tightening = Banks restrict credit | ↓ Easing = Free lending",
        vix: "Implied volatility (fear gauge). Z>2 = Panic | Z<-1 = Complacency. Mean-reverts.",
        tips: "Breakeven (amber): Inflation expectations. Real Rate (blue): True cost of money. 5Y5Y (green): Long-term anchor.",
        bank_reserves: "Total reserves maintained by depository institutions at Federal Reserve Banks. When reserves fall, liquidity stress increases.",
        repo_stress: "Comparison between SOFR (market rate) and IORB (Fed floor). If SOFR stays above IORB, it indicates systemic liquidity shortage.",
        nfp_desc: "Monthly change in employment. <span style='color: #10b981'>>200k: Robust</span> | <span style='color: #f59e0b'>100k-200k: Cooling</span> | <span style='color: #ef4444'><100k: Recessionary Risk</span>",
        jolts_desc: "Total Job Openings. <br><b>Rising:</b> Tight market (Hawkish). <b>Falling:</b> Cooling (Dovish).",
        chart_divergence: "CLI-GLI Divergence (Macro Coupling)",
        divergence_desc: "Measuring the coupling between Credit (CLI) and Liquidity (GLI).",
        div_guide_eq: "Near 0: Equilibrium. System functioning efficiently.",
        div_guide_trap: "Negative (<-1): Liquidity Trap. Money not reaching the economy.",
        div_guide_excess: "Positive (>1): Credit Excess. Bubble risk vs draining liquidity.",
        stat_liq_trap_title: "⚠️ LIQUIDITY TRAP RISK",
        stat_liq_trap_desc: "Liquidity is expanding but credit is not responding. System efficiency is low.",
        latest_value: "Latest Value",
        view_raw: "Raw",
        view_zscore: "Z-Score",
        view_percentile: "Percentile",
        chart_cli_title: "Credit Liquidity Index (CLI Aggregate)",
        yc_inverted: "INVERTED",
        yc_de_inverting: "DE-INVERTING (DANGER)",
        yc_normal: "NORMAL",
        change_1m: "1M Change",
        // Navigation
        nav_dashboard: "Dashboard",
        nav_gli: "Global Flows CB",
        nav_m2: "Global M2",
        nav_us_system: "US System",
        nav_risk_model: "Risk Model",
        nav_btc_analysis: "BTC Analysis",
        nav_btc_quant: "BTC Quant v2",
        nav_fed_forecasts: "Fed Forecasts",
        prob_hike: "Hike",
        prob_hold: "Hold",
        prob_cut: "Cut",
        no_change: "No Change",
        target_rate: "Target Rate",
        implied_rate: "Implied Rate",
        cumulative_cuts: "Cumulative Cuts",
        summary_of_projections: "Summary of Economic Projections",
        fed_dot_plot: "Fed Dot Plot",
        fomc_projections_description: "The 'Dot Plot' shows the FOMC members' projections for the appropriate Federal Funds Rate level at year-end.",
        median: "Median",
        individual_projection: "Individual Projection",
        upcoming_fomc_meetings: "Upcoming FOMC Meetings",
        view_grouped: "Grouped",
        view_individual: "Individual",
        type: "Type",
        any: "Any",
        all: "All",
        term_min: "Term Min",
        term_max: "Term Max",
        min_amount: "Min Amount",
        max_amount: "Max Amount",
        // Header & Global
        header_desc: "Real-time macro liquidity and credit monitoring across 5 major central banks",
        system_live: "System Live",
        refresh_data: "Refresh Data",
        light_mode: "Light Mode",
        dark_mode: "Dark Mode",
        switch_lang: "Switch Language",
        conn_error: "Connection Error:",
        // Stats Cards
        stat_gli: "Global Liquidity (GLI)",
        stat_us_net: "US Net Liquidity",
        stat_cli: "Credit Index (CLI)",
        stat_vix: "Volatility Index",
        // Common Table Labels
        bank: "Bank",
        weight: "Wgt",
        economy: "Economy",
        account: "Account",
        impact_1m: "1M Global Impact",
        impact_3m: "3M Global Impact",
        impact_1y: "1Y Global Impact",
        impact_us: "Impact on Net Liq",
        impact_note_gli: "* Impact = % contribution of bank's 1M move to total Global Liquidity.",
        impact_note_us: "* Imp = Contribution to US Net Liquidity change. RRP/TGA have an inverse effect.",
        last_data: "Last Data:",
        last: "Last",
        freshness: "Age",
        chart_gli_desc: "Sum of 15 major central bank balance sheets in USD.",
        // Chart Headers
        chart_gli_aggregate: "Global Liquidity Index (Aggregate)",
        chart_us_net_liq: "US Net Liquidity Trends",
        chart_fed_assets: "Fed Assets (USD Trillion)",
        chart_us_credit: "US Credit Conditions",
        chart_rrp: "Fed RRP Facility",
        chart_tga: "Treasury General Account (TGA)",
        chart_m2_aggregate: "Global M2 Money Supply (Aggregate)",
        chart_inflation_exp: "Inflation Expectations (TIPS Market)",
        chart_inflation_swap_title: "USD Inflation Swap Rates (Cleveland Fed)",
        inflation_rate_y: "Rate (%)",
        inflation_curve_signal: "Inflation Curve Signal (1Y-2Y)",
        signal_inverted: "INVERTED (Bearish)",
        signal_normal: "NORMAL (Bullish)",
        signal_neutral: "NEUTRAL",
        inflation_inverted_desc: "1Y Swap below 2Y Swap: Market expects imminent cooldown/disinflation.",
        inflation_normal_desc: "1Y Swap above 2Y Swap: Market expects near-term inflation to remain elevated.",
        inflation_neutral_desc: "Curve is flat or mixed.",
        chart_gli_comp: "GLI Composition & Performance",
        chart_m2_comp: "M2 Composition & Performance",
        chart_us_comp: "US System Components Impact",
        chart_bank_reserves: "Bank Reserves vs Net Liquidity",
        chart_repo_stress: "Repo Market Stress (SOFR vs IORB)",
        // Reserves Metrics
        reserves_velocity: "Reserves Velocity",
        roc_3m: "3M ROC",
        spread_zscore: "Spread Z-Score",
        momentum: "Momentum",
        lcr: "LCR",
        reserves_high_stress: "High Stress",
        reserves_normal: "Normal",
        reserves_low_stress: "Low Stress",
        reserves_bullish: "Bullish",
        reserves_bearish: "Bearish",
        reserves_neutral: "Neutral",
        // US System Metrics
        liquidity_score: "Liquidity Score",
        rrp_drain: "RRP Drain",
        weeks_to_empty: "Weeks to Empty",
        tga_deviation: "TGA Deviation",
        fed_momentum_label: "Fed Momentum",
        netliq_roc: "Net Liq ROC",
        liquid_env: "Liquid",
        dry_env: "Dry",
        regime_qe: "QE Mode",
        regime_qt: "QT Mode",
        // Flow/Impulse Metrics
        flow_impulse: "Liquidity Impulse",
        flow_accel: "Acceleration",
        flow_zscore: "Impulse Z-Score",
        flow_desc: "Impulse tracks the rate of change in liquidity flows. Acceleration captures regime shifts.",
        gli_impulse: "GLI Impulse (13W)",
        m2_impulse: "M2 Impulse (13W)",
        cb_contribution: "CB Contribution to ΔGLI",
        // Formatting
        spot_usd: "Spot USD",
        const_fx: "Const FX",
        // BTC Analysis tab
        btc_analysis_title: "BTC Fair Value Model",
        btc_analysis_desc: "Bitcoin fair value derived from global liquidity, M2, and credit conditions. Price above line = overvalued, below = undervalued.",
        current_valuation: "Current Valuation",
        btc_price: "BTC Price",
        fair_value: "Fair Value",
        deviation: "Deviation",
        zscore: "Z-Score",
        lag_analysis: "Predictive Signals: CLI → BTC Lag Analysis",
        roc_window: "ROC Window",
        optimal_lag: "Optimal Lag",
        max_correlation: "Max Correlation",
        interpretation: "Interpretation",
        // BTC Quant v2 tab
        quant_v2_title: "Quant v2: Enhanced Bitcoin Fair Value Model",
        quant_v2_desc: "This model addresses econometric issues in the legacy model:",
        expansion_contraction: "Expansion/Contraction",
        // Executive Dashboard (Dashboard2)
        exec_narrative: "Executive Narrative",
        risk_profile_title: "Risk Profile & Assessment",
        top_risks: "Top Risks",
        top_positives: "Key Positives",
        overall_narrative: "Overall Narrative",
        catalysts_events: "Catalysts & Events",
        macro_score: "Macro Score",
        regime_strength: "Strength",
        liquidity_engine: "Liquidity Engine",
        delta_1w: "Δ 1W",
        tightening: "Tightening",
        easing: "Easing",
        stable: "Stable",
        btc_fundamentals: "BTC Fundamentals",
        price_fair_gap: "Price vs Fair Value",
        valuation_zscore: "Valuation Z-Score",
        drawdown: "Drawdown",
        realized_vol: "Realized Vol (30D)",
        treasury_settlements_title: "Treasury Settlements (Next 7D)",
        settlement_date: "Settlement",
        issue_type: "Issue Type",
        amount_bn: "Amount ($B)",
        rrp_coverage: "RRP Coverage",
        upcoming_settlements: "Upcoming settlements grouped by issue types.",
        total_issues_7d: "Total Issues (7d)",
        total_amount_bn: "Total Amount ($B)",
        repo_corridor_status: "Repo Corridor Status",
        sofr_iorb_spread: "SOFR-IORB Spread",
        gap_to_ceiling: "Gap to Ceiling (SRF)",
        liquidity_flows: "Liquidity Flows",
        net_flow_1d: "Net Flow (1D)",
        streaks_alerts: "Streaks & Alerts",
        srf_usage_alert: "⚠️ SYSTEMIC STRESS: SRF Usage detected!",
        srf_usage_desc: "Banks are borrowing directly from the Fed at the ceiling rate.",
        days_above_floor: "Days above Floor",
        days_of_usage: "Days of SRF Usage",
        normal: "NORMAL",
        high_stress: "HIGH STRESS",
        market_assessment: "MARKET ASSESSMENT",
        next_7d_catalysts: "Next 7 Days Catalysts",
        settlements: "Settlements",
        confidence: "Conf.",
        today: "TODAY",
        target: "Target",
        alerts: "Alerts",
        signal_matrix_title: "Signal Matrix",
        indicator_col: "Indicator",
        value_col: "Value",
        delta_col: "Δ1M",
        signal_col: "Signal",
        flow_momentum_title: "Flow Momentum",
        aggregate_col: "Aggregate",
        impulse_4w_col: "Impulse 4W",
        impulse_13w_col: "Impulse 13W",
        accel_col: "Accel",
        zscore_col: "Z-Score",
        cb_contrib_title: "CB Contribution to ΔGLI (13W)",
        plumbing_title: "Plumbing: Repo & Corridor",
        corridor_status_bps: "CORRIDOR STATUS (BPS)",
        gap_label: "Gap",
        spread_label: "Spr",
        rrp_1w_label: "ΔRRP (1w)",
        srf_usage_label: "SRF Usage",
        sofr_vol_label: "SOFR Vol",
        net_repo_z_label: "Net Repo Z",
        btc_fundamentals_title: "BTC Fundamentals-Lite",
        valuation_premium: "PREMIUM",
        valuation_discount: "DISCOUNT",
        valuation_fair: "FAIR VALUE",
        price_vs_fair: "Price vs Fair",
        valuation_z: "Valuation Z",
        inflation_expect_title: "Inflation Expectations",
        curve_label: "Curve",
        fed_target_label: "Fed Target",
        metric_col: "Metric",
        source_col: "Source",
        delta_pp_col: "Δ1M (pp)",
        roc_1m_col: "ROC 1M",
        roc_3m_col: "ROC 3M",
        stat_fed_assets: "FED ASSETS",
        stat_bank_reserves: "BANK RESERVES",
        stat_rrp_usage: "ON RRP USAGE",
        stat_tga_balance: "TGA BALANCE",
        indicator_cb_breadth: "Central Bank Breadth (% Expanding)",
        indicator_cb_hhi: "Central Bank Concentration (HHI)",
        cb_breadth_desc: "Percentage of CBs expanding (13-week basis). ↑ Bullish.",
        cb_hhi_desc: "HHI Index. High = few banks drive liquidity.",
        imp_col: "Imp",
        impact_note_m2: "Impact = % contribution of local M2 1M move to total Global M2.",
        market_in_transition: "MARKET IN TRANSITION",
        no_major_stress: "No major stress signals detected",
        liquidity_stable: "Liquidity conditions stable",
        monitor_closely: "Monitor closely for regime changes",
        regime_accelerating: "Accelerating",
        regime_decelerating: "Decelerating",
        repo_normal_desc: "Repo markets functioning normally",
        // Dashboard Table Headers
        economy_col: "Economy",
        wgt_col: "Wgt",
        val_1w: "1W",
        val_1m: "1M",
        val_3m: "3M",
        val_6m: "6M",
        val_1y: "1Y",
        // Additional Risk Model Chart Titles
        chart_credit_spreads: "Credit Spreads (HY vs IG)",
        credit_spreads_desc: "High Yield (red) and Investment Grade (Sky Blue) credit spreads. Higher spreads = more risk aversion.",
        spread_type: "Spread",
        current_value: "Current",
        status: "Status",
        st_louis_stress_title: "St. Louis Financial Stress Index (STLFSI4)",
        st_louis_stress_desc: "Weekly index measuring financial stress. Values above 0 = above-average stress.",
        kcfsi_title: "Kansas City Financial Stress Index (KCFSI)",
        kcfsi_desc: "Monthly index from Kansas City Fed. Positive = stress above typical.",
        corporate_yields_title: "Corporate Yields (BAA/AAA)",
        corporate_yields_desc: "BAA (red, lower quality IG) vs AAA (green, highest quality).",
        quality_spread_desc: "BAA-AAA spread = credit quality premium. Wider = more risk aversion.",
        job_openings_title: "Job Openings (JOLTS)",
        job_openings_desc: "Job openings in millions. Higher = tighter labor market. Watch for JOLTS/Unemployed ratio trends.",
        nfp_chart_title: "Non-Farm Payrolls (NFP)",
        nfp_chart_desc: "Monthly change in non-farm payrolls (thousands). Above 150k = healthy, below 0 = contraction.",
        labor_market_signal: "Labor Market Signal",
        labor_demand_signal: "Labor Demand Signal",
        // Composite Risk Panel
        composite_risk_title: "Composite Liquidity Risk Assessment",
        risk_low_desc: "Liquidity conditions are ample. Risk of systemic stress is low.",
        risk_mod_desc: "Conditions are tightening but stable. Monitor repo spreads closely.",
        risk_high_desc: "Persistent stress detected. Potential for liquidity-driven market volatility.",
        risk_crit_desc: "Severe liquidity shortage. Systemic intervention likely required.",
        // Inflation Panel
        inflation_exp_title: "Inflation Expectations (TIPS Market)",
        inflation_swap_title: "USD Inflation Swap Rates (Cleveland Fed)",
        five_yr_tips: "5Y TIPS Breakeven",
        ten_yr_tips: "10Y TIPS Breakeven",
        cpi_actual: "CPI YoY (Actual)",
        cleveland_1y: "Cleveland Fed (1Y)",
        cleveland_2y: "Cleveland Fed (2Y)",
        cleveland_5y: "Cleveland Fed (5Y)",
        cleveland_10y: "Cleveland Fed (10Y)",
        // New Indicators
        stress_critical: "CRITICAL",
        key_risks: "Key Risks",
        key_positives: "Key Positives",
        recommendation: "Recommendation",
        // Inflation Swaps
        chart_tips_vs_swaps: "TIPS vs Inflation Swaps (Cleveland Fed)",
        tips_vs_swaps_desc: "Comparing TIPS Breakeven with Cleveland Fed Expected Inflation (derived from Treasury yields, inflation swaps, and surveys).",
        cleveland_fed: "Cleveland Fed",
        divergence: "Divergence",
        chart_inflation_curve: "Inflation Expectations Curve",
        chart_risk_premium: "Inflation Risk Premium",
        risk_premium_desc: "Risk premium investors require for inflation uncertainty. High values indicate elevated concern.",
        quant_v2_weekly: "Weekly frequency (W-FRI) instead of daily to avoid FRI autocorrelation",
        quant_v2_log: "Δlog(BTC) returns instead of log levels (avoids spurious regression)",
        quant_v2_elastic: "ElasticNet with 1-8 week lags for automatic feature selection",
        quant_v2_pca: "PCA GLI factor instead of raw sum (handles colinearity)",
        quant_v2_vol: "Rolling 52-week volatility for adaptive bands",
        oos_metrics: "Out-of-Sample Metrics",
        model_params: "Model Parameters",
        quant_chart_desc: "Cumulative model drift may cause divergence over time.",
        interp_regression: "Regression using:",
        interp_gli_lag: "GLI (45-day lag)",
        interp_cli_lag: "CLI (14-day lag)",
        interp_vix_coin: "VIX (coincident)",
        interp_netliq_lag: "US Net Liq (30-day lag)",
        interp_zones: "Deviation Zones",
        interp_extreme: "±2σ: Extreme over/undervaluation",
        interp_moderate: "±1σ: Moderate deviation",
        interp_fair_range: "Within ±1σ: Fair value range",
        interp_signals: "Trading Signals",
        interp_profittaking: "Z > +2: Consider profit-taking",
        interp_accumulation: "Z < -2: Potential accumulation",
        interp_divergence: "ROC divergence: Momentum shifts",
        // Data Health & Pulse
        data_health: "Data Health & Coverage",
        series: "Series",
        real_date: "Real Date",
        coverage: "Coverage",
        active_cbs: "Active CBs",
        impulse_analysis: "Liquidity Impulse Analysis",
        chart_impulse_desc: "Comparing the momentum of GLI, Net Liquidity, and Credit conditions (Normalized Z-Scores). Divergences often lead BTC price action.",
        btc_roc_overlay: "BTC ROC Overlay",
        period: "Period",
        lag_days: "Lag (Days)",
        // Macro Regimes
        regime_bullish: "Bullish Macro",
        regime_bearish: "Bearish Macro",
        regime_global_inj: "Global Injection",
        regime_us_inj: "US Injection",
        regime_early_warning: "Early Warning",
        regime_losing_steam: "Losing Steam",
        regime_neutral: "Neutral / Transition",
        regime_signal: "Macro Pulse & Regime",
        regime_chart_desc: "Log-scale BTC Price overlaid on Macro Regime. Background tracks combined Global (GLI) and US (NetLiq) liquidity momentum. Green: Dual Expansion (Bullish). Red: Dual Contraction (Bearish). Grey: Mixed/Neutral.",
        regime_formula_title: "Regime Formula",
        percentile: "Percentile",
        regime_formula_desc: "Score = 50 + 15 × Total_Z | Liquidity (35% GLI + 35% NetLiq + 20% M2 ± CB breadth) + Credit (60% CLI + 40% CLI momentum) - Brakes (real rates + repo stress + reserve scarcity)",
        regime_score_bullish: "Score > 50: Bullish bias (green) → Liquidity expanding, credit easing",
        regime_score_bearish: "Score < 50: Bearish bias (red) → Liquidity contracting, credit tightening",
        // Risk Model Tab
        risk_stance: "STANCE",
        risk_factors: "Factors",
        risk_bullish: "Bullish",
        risk_bearish: "Bearish",
        status_bullish: "BULLISH",
        status_bearish: "BEARISH",
        status_neutral: "NEUTRAL",
        status_warning: "WARNING",
        status_ok: "OK",
        status_stress: "STRESS",
        tips_breakeven: "Breakeven",
        tips_real_rate: "Real Rate",
        tips_fwd: "5Y5Y Forward",
        tips_be_desc: "Inflation expectations",
        tips_rr_desc: "Cost of money",
        tips_fwd_desc: "Long-term anchor",
        tips_signal_label: "TIPS Macro Signal",
        cli_stance: "CLI STANCE",
        cli_top_30: "Top 30%",
        cli_bottom_30: "Bottom 30%",
        cli_mid_range: "Middle range",
        cli_desc_ext: "↑ CLI = Easier credit (bullish) ↓ Contraction = Tighter (bearish)",
        repo_rate: "Rate",
        repo_value: "Value",
        repo_spread_sig: "Spread/Signal",
        credit_hy_name: "HY Spread Contrast",
        credit_hy_desc: "High Yield spread vs Treasury. Higher = Risk-off, Lower = Risk-on.",
        credit_ig_name: "IG Spread Contrast",
        credit_ig_desc: "Investment Grade spreads. Higher = Credit stress, Lower = Credit solid.",
        credit_nfci_credit_name: "Credit (NFCI)",
        credit_nfci_credit_desc: "Chicago Fed National Financial Conditions (Credit Subindex).",
        credit_nfci_risk_name: "Risk (NFCI)",
        credit_nfci_risk_desc: "Chicago Fed National Financial Conditions (Risk Subindex).",
        credit_lending_name: "Lending (SLOOS)",
        credit_lending_desc: "Senior Loan Officer Opinion Survey. Net % Banks tightening.",
        credit_vix_name: "Volatility (VIX)",
        credit_vix_desc: "CBOE Volatility Index. Higher = Fear/Stress, Lower = Complacency.",
        indicator_move_name: "MOVE Index Contrast",
        indicator_move_desc: "ICE BofA MOVE Index. Measures implied bond volatility. Higher = Stress.",
        indicator_fx_vol_name: "DXY Realized Volatility",
        indicator_fx_vol_desc: "21-day realized volatility of the US Dollar Index. Measures currency market stress.",
        signal_status: "Signal Status",
        roc_title: "Momentum Pulse (ROC)",
        roc_factor: "Factor",
        indicator_gli: "Global GLI",
        indicator_netliq: "US Net Liquidity",
        indicator_cli: "Credit (CLI)",
        indicator_real_rates: "Real Rates (5Y)",
        indicator_vix: "Volatility (VIX)",
        indicator_move: "MOVE Index (Bonds)",
        indicator_fxvol: "FX Volatility (EVZ)",
        indicator_fed: "Fed Assets",
        indicator_ecb: "ECB Assets",
        indicator_boj: "BoJ Assets",
        indicator_boe: "BoE Assets",
        indicator_pboc: "PBoC Assets",
        indicator_boc: "BoC Assets",
        indicator_rba: "RBA Assets",
        indicator_snb: "SNB Assets",
        indicator_bok: "BoK Assets",
        indicator_rbi: "RBI Assets",
        indicator_cbr: "CBR Assets",
        indicator_bcb: "BCB Assets",
        indicator_rbnz: "RBNZ Assets",
        indicator_sr: "Sveriges Riksbank",
        indicator_bnm: "BNM Assets",
        indicator_us_m2: "US M2",
        indicator_eu_m2: "Eurozone M2",
        indicator_cn_m2: "China M2",
        indicator_jp_m2: "Japan M2",
        indicator_uk_m2: "UK M2",
        indicator_ca_m2: "Canada M2",
        indicator_au_m2: "Australia M2",
        indicator_in_m2: "India M2",
        indicator_ch_m2: "Switzerland M2",
        indicator_ru_m2: "Russia M2",
        indicator_br_m2: "Brazil M2",
        indicator_kr_m2: "S. Korea M2",
        indicator_mx_m2: "Mexico M2",
        indicator_my_m2: "Malaysia M2",
        // Signal Reasons - HY Spread
        signal_hy_bullish: "HY spread contracted: risk appetite, easy credit.",
        signal_hy_bearish: "HY spread widened: risk aversion, credit stress.",
        signal_hy_neutral: "HY spread in normal range, no extreme signal.",
        // Signal Reasons - IG Spread
        signal_ig_bullish: "IG spread low: solid credit conditions.",
        signal_ig_bearish: "IG spread elevated: credit market tension.",
        signal_ig_neutral: "IG spread stable, normal conditions.",
        // Signal Reasons - NFCI Credit
        signal_nfci_credit_bullish: "NFCI Credit negative: loose credit conditions.",
        signal_nfci_credit_bearish: "NFCI Credit positive: restrictive credit conditions.",
        signal_nfci_credit_neutral: "NFCI Credit neutral, no extreme pressure.",
        // Signal Reasons - NFCI Risk
        signal_nfci_risk_bullish: "NFCI Risk low: systemic risk contained.",
        signal_nfci_risk_bearish: "NFCI Risk elevated: higher perceived systemic risk.",
        signal_nfci_risk_neutral: "NFCI Risk at normal levels.",
        // Signal Reasons - Lending
        signal_lending_bullish: "Credit standards relaxed: credit expansion.",
        signal_lending_bearish: "Restrictive standards: credit contraction.",
        signal_lending_neutral: "Lending standards unchanged.",
        // Signal Reasons - VIX
        signal_vix_bullish: "VIX low: market complacency/confidence.",
        signal_vix_bearish: "VIX elevated: fear and market volatility.",
        signal_vix_neutral: "VIX in normal range, moderate volatility.",
        // Signal Reasons - CLI
        signal_cli_bullish: "CLI indicates credit expansion and risk appetite.",
        signal_cli_bearish: "CLI indicates credit contraction and risk aversion.",
        signal_cli_neutral: "CLI neutral, balanced liquidity conditions.",
        // Signal Reasons - Repo
        signal_repo_bullish: "SOFR ≈ IORB: adequate interbank liquidity.",
        signal_repo_bearish: "SOFR >> IORB: repo liquidity stress.",
        signal_repo_neutral: "Repo spread in normal range.",
        signal_repo_warning: "SOFR << IORB: excess liquidity (unusual).",
        // Signal Reasons - TIPS
        signal_tips_bullish: "Reflation: High BE + Low RR. Fed dovish, economic expansion.",
        signal_tips_bearish: "Tightening: High RR + Low BE. Fed hawkish, monetary restriction.",
        signal_tips_neutral: "Goldilocks: BE & RR in normal range, macro equilibrium.",
        signal_tips_warning: "Stagflation: High inflation + Fed hawkish. Adverse conditions.",
        signal_tips_disinflation: "Disinflation: Low BE & RR. Possible slowdown or deflation.",
        signal_move_bullish: "MOVE low: stable bond market/liquidity.",
        signal_move_bearish: "MOVE high: bond market stress/reprising.",
        signal_move_neutral: "MOVE average: normal bond volatility.",
        signal_fx_vol_bullish: "FX Vol low: stable global flows.",
        signal_fx_vol_bearish: "FX Vol high: currency market stress.",
        signal_fx_vol_neutral: "FX Vol average: normal currency volatility.",
        // Regimes Tab
        nav_regimes: "Regimes",
        regimes_header: "Macro Regimes",
        regimes_header_desc: "Quantitative regime classification using liquidity, credit, growth, and monetary brake indicators.",
        regime_v2a_title: "V2A: Inflation-Aware Regime",
        regime_v2a_formula: "Score = 50×Liquidity + 25×Credit + 25×Brakes",
        regime_v2a_desc: "Focuses on inflation pressures via monetary brakes. Suitable for high-inflation environments.",
        regime_v2b_title: "V2B: Growth-Aware Regime",
        regime_v2b_formula: "Score = 40×Liquidity + 25×Credit + 20×Growth + 15×Brakes",
        regime_v2b_desc: "Balances growth momentum with credit conditions. Better for growth-focused analysis.",
        regime_bullish_label: "BULLISH",
        regime_bearish_label: "BEARISH",
        regime_neutral_label: "NEUTRAL",
        regime_bullish_desc: "Dual expansion: Both global and domestic liquidity expanding. Credit conditions easing.",
        regime_bearish_desc: "Dual contraction: Both global and domestic liquidity contracting. Credit tightening.",
        regime_neutral_desc: "Mixed/divergent regime: Conflicting signals between global and domestic conditions.",
        regime_current_values: "Current Values",
        regime_liquidity: "Liquidity",
        regime_credit: "Credit",
        regime_growth: "Growth",
        regime_brakes: "Brakes",
        regime_total_z: "Total Z",
        regime_btc_overlay_v2a: "BTC + Regime V2A (Inflation-Aware)",
        regime_btc_overlay_v2b: "BTC + Regime V2B (Growth-Aware)",
        regime_btc_desc: "Log-scale BTC Price overlaid on Macro Regime. Green: Dual Expansion (Bullish). Red: Dual Contraction (Bearish). Grey: Mixed/Neutral.",
        cli_v1_label: "CLI V1 (Original)",
        cli_v2_label: "CLI V2 (Enhanced)",
        cli_comparison_title: "CLI V1 vs V2 Comparison",
        cli_v2_formula: "CLI V2 = HY Spread + HY Momentum + IG Spread + NFCI Credit/Risk + Lending + MOVE + FX Vol + Yield Curve + Real Rate Shock",
        block_decomposition_title: "Regime Block Decomposition",
        block_decomp_desc: "Contribution of each block (Liquidity, Credit, Growth, Brakes) to the total score. Z-Score normalized.",
        stress_historical_title: "Historical Stress Dashboard",
        stress_historical_desc: "Inflation (7) + Liquidity (7) + Credit (7) + Volatility (6) = 27 max. Levels: LOW (0-4), MODERATE (5-9), HIGH (10-14), CRITICAL (15+).",

        // RiskModelTab Supplement
        chart_treasury_10y: "10Y UST Yield (%)",
        chart_treasury_10y_z: "10Y Yield (Z-Score)",
        chart_treasury_10y_pct: "10Y Yield (Percentile)",
        chart_treasury_2y: "2Y UST Yield (%)",
        chart_treasury_2y_z: "2Y Yield (Z-Score)",
        chart_treasury_2y_pct: "2Y Yield (Percentile)",
        chart_treasury_30y: "30Y UST Yield (%)",
        chart_treasury_30y_z: "30Y Yield (Z-Score)",
        chart_treasury_30y_pct: "30Y Yield (Percentile)",
        chart_yield_curve_z: "Yield Curve (Z-Score)",
        chart_stlfsi4_raw: "STLFSI4 (Raw)",
        chart_kcfsi_raw: "KCFSI (Raw)",
        repo_srf_ceiling: "SRF Rate (Ceiling)",
        repo_iorb_floor: "IORB (Floor)",
        legend_1y: "1Y",
        legend_2y: "2Y",
        legend_5y: "5Y",
        legend_10y: "10Y",
        chart_inflation_exp_1y: "1Y Inflation Exp. (%)",
        chart_inflation_exp_2y: "2Y Inflation Exp. (%)",
        chart_inflation_exp_5y: "5Y Inflation Exp. (%)",
        chart_inflation_exp_10y: "10Y Inflation Exp. (%)",
        chart_nfci_credit: "NFCI Credit",
        chart_nfci_risk: "NFCI Risk",
        spread_1y_2y: "Spread (1Y-2Y)",

        // BtcAnalysisTab Supplements
        model_macro: "Macro Liquidity",
        model_adoption: "Macro + Adoption",
        window_7d: "7-Day",
        window_14d: "14-Day",
        window_30d: "30-Day",
        freq_weekly: "Weekly",

        // RegimesTab Supplements
        // stress_critical: "CRITICAL", // Duplicate
        stress_high: "HIGH",
        stress_moderate: "MODERATE",
        stress_low: "LOW",
        stress_inflation: "Inflation",
        stress_liquidity: "Liquidity",
        stress_credit: "Credit",
        stress_volatility: "Volatility",
        stress_score_y: "Stress Score",
        regime_score_label: "SCORE",
        best_offset_label: "Best Offset",
        calculate_label: "Calculate",
        offset_days_label: "Offset (Days):",
        regime_v2a_score_title: "Macro Regime V2A Score",
        regime_v2b_score_title: "Macro Regime V2B Score",

        // Dashboard2 Supplements
        rrp_buffer: "RRP Buffer",
        no_major_settlements: "No major settlements next 7d",
        stress_panel_title: "Market Stress Dashboard",
        risk_on_label: "RISK-ON",
        risk_off_label: "RISK-OFF",
        neutral_label: "NEUTRAL",
        supportive_factors: "SUPPORTIVE FACTORS",
        loading_analysis: "Loading analysis...",
        loading: "Loading...",
        no_data: "No data",
        stress_global: "Global Stress Level",
        reserves_t: "Bank Reserves (T)",
        net_liq_t: "Net Liquidity (T)",
        reserves_axis: "Reserves (T)",
        net_liq_axis: "Net Liq (T)",

        // UsSystemTab Risk Assessment
        overall_risk_level: "Overall Risk Level",
        risk_level_critical: "CRITICAL",
        risk_level_moderate: "MODERATE",
        risk_level_caution: "CAUTION",
        risk_level_low: "LOW",
        risk_summary_critical: "High risk of funding crunch. Immediate Fed intervention likely needed.",
        risk_summary_moderate: "Evolving stress detected. Monitor rate decoupling and SRF usage.",
        risk_summary_caution: "Liquidity buffer narrowing. Watch RRP depletion.",
        risk_summary_low: "Adequate liquidity. System functioning correctly.",
        risk_reserves_critical: "Critical Reserves Scarce (<$2.5T)",
        risk_reserves_low: "Reserves approaching comfortable floor (<$2.8T)",
        risk_sofr_stress: "Severe funding stress (SOFR >> IORB)",
        risk_sofr_decoupling: "Market rate decoupling from Fed floor",
        risk_srf_active: "Active SRF Usage",

        // UsSystemTab Regime Labels
        regime_injection: "INJECTION",
        regime_heavy_drain: "HEAVY DRAIN",
        regime_drain: "DRAIN",

        // UsSystemTab Repo Panel
        net_pos_label: "Net Position",
        regime_label: "Regime",
        srf_inject_label: "SRF (Inject)",
        rrp_drain_label: "RRP (Drain)",
        net_repo_operations: "Net Repo Operations",
        net_repo_desc: "Net = SRF Usage (injection) - RRP Usage (drain). Positive = Fed adding liquidity. Negative = Fed removing liquidity.",

        // UsSystemTab SOFR Corridor
        sofr_corridor_desc: "SOFR should trade between IORB (floor) and SRF Rate (ceiling). Approaching ceiling or SRF usage signals funding stress.",
        sofr_volume_desc: "SOFR transaction volume measures repo market depth. Falling volume = early warning of dysfunction.",

        // RiskModelTab Treasury Yields
        treasury_10y_desc: "10-Year Treasury Constant Maturity Yield. Key benchmark rate.",
        treasury_2y_desc: "2-Year Treasury Constant Maturity Yield. Short-term rate.",
        yield_curve_30y10y_desc: "Long term curve steepness. Inversion = severe stress.",

        // UsDebtTab - Treasury Maturity Tracker
        us_debt_tab: "US Debt",
        treasury_maturity_tracker: "Treasury Maturity Tracker",
        demo_data: "DEMO DATA",
        peak_maturity_month: "Peak Maturity Month",
        highest_refinancing: "Highest refinancing",
        peak_amount: "Peak Amount",
        single_month_max: "Single month maximum",
        bills_outstanding: "Bills Outstanding",
        short_term_debt: "Short-term debt",
        total_outstanding: "Total Outstanding",
        marketable_debt: "Marketable debt",
        next_12m_refinancing: "Next 12M Refinancing",
        must_be_rolled: "Must be rolled over",
        forecast_horizon: "Forecast Horizon",
        months_abbr: "Mo",
        projection_period: "Projection period",
        maturity_schedule_title: "Maturity Schedule by Security Type",
        stacked: "Stacked",
        line: "Line",
        monthly_maturity_schedule: "Monthly Maturity Schedule ($ Billions)",
        updated: "Updated",
        treasury_bills: "Treasury Bills",
        treasury_notes: "Treasury Notes",
        treasury_bonds: "Treasury Bonds",
        amount_billions: "Amount ($ Billions)",
        loading_treasury_data: "Loading treasury data...",
        source: "Source",
        total: "Total",
        month: "Month",
    },
    es: {
        gli: "Suma de los balances de 15 bancos centrales en USD. ↑ Expansión = Inyección de liquidez (alcista) | ↓ Contracción = QT (bajista)",
        gli_cb: "Activos individuales de bancos centrales en USD. Mayor = más peso en liquidez global.",
        btc_fair: "Valor justo de BTC derivado de factores macro. Precio arriba = sobrevalorado, abajo = infravalorado.",
        btc_bands: "Bandas ±1σ/2σ muestran rango de desviación histórica. Revierte a la media.",
        net_liq: "Balance de la Fed menos TGA y RRP. Motor clave de liquidez del dólar.",
        rrp: "Repo Inverso drena liquidez del sistema. ↓ RRP = Liberación de liquidez (alcista) | ↑ RRP = Drenaje de liquidez (bajista)",
        tga: "Cuenta General del Tesoro. ↓ TGA = Gasto del Tesoro = Inyección de liquidez | ↑ TGA = Ahorro del Tesoro = Drenaje de liquidez",
        m2_global: "Oferta monetaria global en USD. Indicador adelantado de precios (45-90 días de retardo).",
        m2_country: "M2 del país en moneda local convertida a USD.",
        cli: "Agrega condiciones crediticias, volatilidad y préstamos. ↑ CLI = Crédito fácil (alcista) | ↓ CLI = Más estricto",
        hy_spread: "Spreads de bonos High Yield vs Treasuries. ↓ Spread = Risk-on (alcista) | ↑ = Risk-off",
        ig_spread: "Spreads de grado de inversión. ↓ Spread = Crédito relajado | ↑ = Estrés crediticio",
        nfci_credit: "Subíndice de crédito NFCI de la Fed. ↓ Bajo 0 = Condiciones laxas | ↑ Sobre 0 = Estrictas",
        nfci_risk: "Subíndice de riesgo NFCI. ↓ Bajo 0 = Bajo miedo | ↑ Sobre 0 = Miedo elevado",
        lending: "Encuesta de préstamos bancarios. ↑ Endurecimiento = Restringen crédito | ↓ = Prestan libremente",
        vix: "Volatilidad implícita (indicador de miedo). Z>2 = Pánico | Z<-1 = Complacencia.",
        tips: "Breakeven (ámbar): Expectativas de inflación. Tasa Real (azul): Coste real del dinero. 5Y5Y (verde): Anclaje a largo plazo.",
        bank_reserves: "Reservas totales mantenidas por instituciones depositarias en los Bancos de la Reserva Federal. Cuando las reservas caen, el estrés de liquidez aumenta.",
        repo_stress: "Comparativa entre el SOFR (tipo de mercado) y el IORB (suelo de la Fed). Si el SOFR se mantiene por encima del IORB, indica escasez sistémica de liquidez.",
        nfp_desc: "Cambio mensual en el empleo. <span style='color: #10b981'>>200k: Robusto</span> | <span style='color: #f59e0b'>100k-200k: Enfriamiento</span> | <span style='color: #ef4444'><100k: Riesgo Recesivo</span>",
        jolts_desc: "Vacantes de empleo totales. <br><b>Subiendo:</b> Mercado tenso (Hawkish). <b>Bajando:</b> Enfriamiento (Dovish).",
        chart_divergence: "Divergencia CLI-GLI (Acoplamiento Macro)",
        divergence_desc: "Medición del acoplamiento entre el Crédito (CLI) y la Liquidez (GLI).",
        div_guide_eq: "Cerca de 0: Equilibrio. El sistema funciona eficientemente.",
        div_guide_trap: "Negativo (<-1): Trampa de Liquidez. El dinero no llega a la calle.",
        div_guide_excess: "Positivo (>1): Exceso de Crédito. Riesgo de burbuja frente a liquidez drenándose.",
        stat_liq_trap_title: "⚠️ RIESGO DE TRAMPA DE LIQUIDEZ",
        stat_liq_trap_desc: "La liquidez se expande pero el crédito no responde. Baja eficiencia del sistema.",
        latest_value: "Último Valor",
        view_raw: "Original",
        view_zscore: "Z-Score",
        view_percentile: "Percentil",
        chart_cli_title: "Índice de Liquidez Crediticia (CLI Agregado)",
        yc_inverted: "INVERTIDA",
        yc_de_inverting: "DES-INVERSIÓN (PELIGRO)",
        yc_normal: "NORMAL",
        change_1m: "Cambio 1M",
        // Navigation
        nav_dashboard: "Panel de Control",
        nav_gli: "Flujos Globales CB",
        nav_m2: "M2 Global",
        nav_us_system: "Sistema EE.UU.",
        nav_risk_model: "Modelo de Riesgo",
        nav_btc_analysis: "Análisis BTC",
        nav_btc_quant: "BTC Quant v2",
        nav_fed_forecasts: "Pronósticos de la Fed",
        prob_hike: "Subida",
        prob_hold: "Mantener",
        prob_cut: "Recorte",
        no_change: "Sin Cambio",
        target_rate: "Tasa Objetivo",
        implied_rate: "Tasa Implícita",
        cumulative_cuts: "Recortes Acumulados",
        summary_of_projections: "Resumen de Proyecciones Económicas",
        fed_dot_plot: "Diagrama de Puntos de la Fed (Dot Plot)",
        fomc_projections_description: "El 'Dot Plot' muestra las proyecciones de los miembros del FOMC para el nivel adecuado de la Tasa de Fondos Federales al final del año.",
        median: "Mediana",
        individual_projection: "Proyección Individual",
        upcoming_fomc_meetings: "Próximas Reuniones del FOMC",
        view_grouped: "Agrupado",
        view_individual: "Individual",
        type: "Tipo",
        any: "Cualquiera",
        all: "Todo",
        term_min: "Plazo Mín",
        term_max: "Plazo Máx",
        min_amount: "Monto Mín",
        max_amount: "Monto Máx",
        expansion_contraction: "Expansión/Contracción",
        // Executive Dashboard (Dashboard2)
        exec_narrative: "Análisis Ejecutivo",
        risk_profile_title: "Perfil de Riesgo y Evaluación",
        top_risks: "Riesgos Principales",
        top_positives: "Aspectos Positivos",
        overall_narrative: "Narrativa General",
        catalysts_events: "Catalizadores y Eventos",
        macro_score: "Puntuación Macro",
        regime_strength: "Fuerza",
        liquidity_engine: "Motor de Liquidez",
        delta_1w: "Δ 1S",
        tightening: "Endurecimiento",
        easing: "Relajación",
        stable: "Estable",
        btc_fundamentals: "Fundamentos BTC",
        price_fair_gap: "Precio vs Valor Justo",
        valuation_zscore: "Z-Score de Valoración",
        drawdown: "Caída Máxima",
        realized_vol: "Vol Realizada (30D)",
        treasury_settlements_title: "Liquidaciones del Tesoro (Próximos 7D)",
        settlement_date: "Liquidación",
        issue_type: "Tipo de Emisión",
        amount_bn: "Monto ($B)",
        rrp_coverage: "Cobertura RRP",
        upcoming_settlements: "Próximas liquidaciones agrupadas por tipos de emisión.",
        total_issues_7d: "Total Emisiones (7d)",
        total_amount_bn: "Monto Total ($B)",
        repo_corridor_status: "Estado del Corredor Repo",
        sofr_iorb_spread: "Diferencial SOFR-IORB",
        gap_to_ceiling: "Brecha al Techo (SRF)",
        liquidity_flows: "Flujos de Liquidez",
        net_flow_1d: "Flujo Neto (1D)",
        streaks_alerts: "Rachas y Alertas",
        srf_usage_alert: "⚠️ ESTRÉS SISTÉMICO: ¡Uso de SRF detectado!",
        srf_usage_desc: "Los bancos están tomando prestado directamente de la Fed a la tasa de techo.",
        days_above_floor: "Días sobre el Suelo",
        days_of_usage: "Días de Uso del SRF",
        normal: "NORMAL",
        high_stress: "ALTO ESTRÉS",
        market_assessment: "EVALUACIÓN DE MERCADO",
        next_7d_catalysts: "Catalizadores Próximos 7D",
        settlements: "Liquidaciones",
        confidence: "Conf.",
        today: "HOY",
        target: "Objetivo",
        alerts: "Alertas",
        signal_matrix_title: "Matriz de Señales",
        indicator_col: "Indicador",
        value_col: "Valor",
        delta_col: "Δ1M",
        signal_col: "Señal",
        flow_momentum_title: "Momento de Flujos",
        aggregate_col: "Agregado",
        impulse_4w_col: "Impulso 4S",
        impulse_13w_col: "Impulso 13S",
        accel_col: "Acel",
        zscore_col: "Z-Score",
        cb_contrib_title: "Contribución CB a ΔGLI (13S)",
        plumbing_title: "Plumbing: Repo y Corredor",
        corridor_status_bps: "ESTADO DEL CORREDOR (BPS)",
        gap_label: "Brecha",
        spread_label: "Spread",
        rrp_1w_label: "ΔRRP (1s)",
        srf_usage_label: "Uso SRF",
        sofr_vol_label: "Vol SOFR",
        net_repo_z_label: "Net Repo Z",
        btc_fundamentals_title: "Fundamentos BTC (Lite)",
        valuation_premium: "PRIMA",
        valuation_discount: "DESCUENTO",
        valuation_fair: "VALOR JUSTO",
        price_vs_fair: "Precio vs Justo",
        valuation_z: "Z de Valoración",
        inflation_expect_title: "Expectativas de Inflación",
        curve_label: "Curva",
        fed_target_label: "Obj. Fed",
        metric_col: "Métrica",
        source_col: "Fuente",
        delta_pp_col: "Δ1M (pp)",
        roc_1m_col: "ROC 1M",
        roc_3m_col: "ROC 3M",
        stat_fed_assets: "ACTIVOS FED",
        stat_bank_reserves: "RESERVAS BANCARIAS",
        stat_rrp_usage: "USO ON RRP",
        stat_tga_balance: "SALDO TGA",
        indicator_cb_breadth: "Amplitud de Bancos Centrales (% Expandiendo)",
        indicator_cb_hhi: "Concentración de Bancos Centrales (HHI)",
        cb_breadth_desc: "Porcentaje de BC expanding (base 13 semanas). ↑ Alcista.",
        cb_hhi_desc: "Índice HHI. Alto = pocos bancos impulsan la liquidez.",
        imp_col: "Imp",
        impact_note_m2: "Impacto = % contribución del movimiento local de M2 1M al total de M2 Global.",
        market_in_transition: "MERCADO EN TRANSICIÓN",
        no_major_stress: "No se detectan señales de estrés importantes",
        liquidity_stable: "Condiciones de liquidez estables",
        monitor_closely: "Monitorear de cerca cambios de régimen",
        regime_accelerating: "Acelerando",
        regime_decelerating: "Desacelerando",
        repo_normal_desc: "Mercados de repo funcionando normalmente",
        // Dashboard Table Headers
        economy_col: "Economía",
        wgt_col: "Peso",
        val_1w: "1S",
        val_1m: "1M",
        val_3m: "3M",
        val_6m: "6M",
        val_1y: "1A",
        // Additional Risk Model Chart Titles
        chart_credit_spreads: "Spreads de Crédito (HY vs IG)",
        credit_spreads_desc: "Diferenciales de crédito High Yield (rojo) y Grado de Inversión (azul cielo). Mayores spreads = más aversión al riesgo.",
        spread_type: "Diferencial",
        current_value: "Actual",
        status: "Estado",
        st_louis_stress_title: "Índice de Estrés Financiero de St. Louis (STLFSI4)",
        st_louis_stress_desc: "Índice semanal que mide el estrés financiero. Valores superiores a 0 = estrés superior a la media.",
        kcfsi_title: "Índice de Estrés Financiero de Kansas City (KCFSI)",
        kcfsi_desc: "Índice mensual de la Fed de Kansas City. Positivo = estrés superior al habitual.",
        corporate_yields_title: "Rendimientos Corporativos (BAA/AAA)",
        corporate_yields_desc: "BAA (rojo, menor calidad IG) vs AAA (verde, máxima calidad).",
        quality_spread_desc: "Diferencial BAA-AAA = prima de calidad crediticia. Más amplio = más aversión al riesgo.",
        job_openings_title: "Vacantes de Empleo (JOLTS)",
        job_openings_desc: "Vacantes de empleo en millones. Mayor = mercado laboral más tenso. Vigilar tendencias del ratio JOLTS/Desempleados.",
        nfp_chart_title: "Nóminas No Agrícolas (NFP)",
        nfp_chart_desc: "Cambio mensual en nóminas no agrícolas (miles). Sobre 150k = saludable, bajo 0 = contracción.",
        labor_market_signal: "Señal del Mercado Laboral",
        labor_demand_signal: "Señal de Demanda Laboral",
        // Composite Risk Panel
        composite_risk_title: "Evaluación Compuesta de Riesgo de Liquidez",
        risk_low_desc: "Las condiciones de liquidez son amplias. El riesgo de estrés sistémico es bajo.",
        risk_mod_desc: "Las condiciones se están endureciendo pero son estables. Monitorear de cerca los spreads de repo.",
        risk_high_desc: "Estrés persistente detectado. Potencial de volatilidad de mercado impulsada por la liquidez.",
        risk_crit_desc: "Grave escasez de liquidez. Es probable que se requiera intervención sistémica.",
        // Inflation Panel
        inflation_exp_title: "Expectativas de Inflación (Mercado TIPS)",
        inflation_swap_title: "Tasas Swap de Inflación USD (Cleveland Fed)",
        five_yr_tips: "Breakeven TIPS 5A",
        ten_yr_tips: "Breakeven TIPS 10A",
        cpi_actual: "IPC Anual (Real)",
        cleveland_1y: "Fed de Cleveland (1A)",
        cleveland_2y: "Fed de Cleveland (2A)",
        cleveland_5y: "Fed de Cleveland (5A)",
        cleveland_10y: "Fed de Cleveland (10A)",
        // New Indicators
        stress_volatility: "Tensión Volatilidad",
        stress_low: "BAJO",
        stress_moderate: "MODERADO",
        stress_high: "ALTO",
        stress_critical: "CRÍTICO",
        key_risks: "Riesgos Clave",
        key_positives: "Aspectos Positivos",
        recommendation: "Recomendación",
        // Inflation Swaps
        chart_tips_vs_swaps: "TIPS vs Inflation Swaps (Cleveland Fed)",
        tips_vs_swaps_desc: "Comparando TIPS Breakeven con Cleveland Fed Expected Inflation (derivado de yields, swaps y encuestas).",
        cleveland_fed: "Cleveland Fed",
        divergence: "Divergencia",
        chart_inflation_curve: "Curva de Expectativas de Inflación",
        chart_risk_premium: "Prima de Riesgo de Inflación",
        risk_premium_desc: "Prima que inversores exigen por incertidumbre de inflación. Valores altos = preocupación elevada.",
        cpi_inflation_yoy: "Inflación IPC (Anual)",
        cpi_description: "Cambio interanual del Índice de Precios al Consumidor. Objetivo: 2%",
        headline_cpi: "IPC General",
        core_cpi: "IPC Subyacente",
        pce_inflation_yoy: "Inflación PCE (Anual)",
        pce_description: "Gastos de Consumo Personal (medida preferida de la Fed). Objetivo: 2%",
        headline_pce: "PCE General",
        core_pce: "PCE Subyacente",
        ism_pmi: "PMI ISM",
        pmi_description: "PMI Manufacturero y de Servicios. Por encima de 50 = Expansión, Por debajo de 50 = Contracción",
        manufacturing: "Manufactura",
        services: "Servicios",
        unemployment_description: "Tasa de desempleo de EE. UU. Indicador clave para el doble mandato de la Fed.",
        current: "Actual",
        // Header & Global
        header_desc: "Monitoreo en tiempo real de liquidez macro y crédito en 5 bancos centrales",
        system_live: "Sistema en Vivo",
        refresh_data: "Actualizar Datos",
        light_mode: "Modo Claro",
        dark_mode: "Modo Oscuro",
        switch_lang: "Cambiar Idioma",
        conn_error: "Error de Conexión:",
        // Stats Cards
        stat_gli: "Liquidez Global (GLI)",
        stat_us_net: "Liquidez Neta EE.UU.",
        stat_cli: "Índice de Crédito (CLI)",
        stat_vix: "Índice de Volatilidad",
        // Common Table Labels
        bank: "Banco",
        weight: "Peso",
        economy: "Economía",
        account: "Cuenta",
        impact_1m: "Impacto Global 1M",
        impact_3m: "Impacto Global 3M",
        impact_1y: "Impacto Global 1Y",
        impact_us: "Impacto en Liq Neta",
        impact_note_gli: "* Impacto = % contribución del movimiento 1M del banco a la Liquidez Global total.",
        impact_note_us: "* Imp = Contribución al cambio de Liquidez Neta de EE.UU. RRP/TGA tienen un efecto inverso.",
        last_data: "Últimos Datos:",
        last: "Último:",
        // Chart Headers
        chart_gli_aggregate: "Índice de Liquidez Global (Agregado)",
        chart_us_net_liq: "Tendencias de Liquidez Neta EE.UU.",
        chart_fed_assets: "Activos de la Fed (Trillones USD)",
        chart_us_credit: "Condiciones Crediticias EE.UU.",
        chart_rrp: "Facilidad RRP de la Fed",
        chart_tga: "Cuenta General del Tesoro (TGA)",
        chart_m2_aggregate: "Oferta Monetaria M2 Global (Agregada)",
        chart_inflation_exp: "Expectativas de Inflación (Mercado TIPS)",
        chart_inflation_swap_title: "Tasas Swap de Inflación USD (Cleveland Fed)",
        inflation_rate_y: "Tasa (%)",
        inflation_curve_signal: "Señal de Curva de Inflación (1Y-2Y)",
        signal_inverted: "INVERTIDA (Bajista)",
        signal_normal: "NORMAL (Alcista)",
        signal_neutral: "NEUTRAL",
        inflation_inverted_desc: "Swap 1Y bajo Swap 2Y: El mercado espera enfriamiento o desinflación inminente.",
        inflation_normal_desc: "Swap 1Y sobre Swap 2Y: El mercado espera que la inflación a corto plazo siga elevada.",
        inflation_neutral_desc: "La curva es plana o mixta.",
        chart_gli_comp: "Composición y Rendimiento de GLI",
        chart_m2_comp: "Composición y Rendimiento de M2",
        chart_us_comp: "Impacto de Componentes del Sistema EE.UU.",
        chart_bank_reserves: "Reservas Bancarias vs Liquidez Neta",
        chart_repo_stress: "Estrés del Mercado Repo (SOFR vs IORB)",
        // Reserves Metrics
        reserves_velocity: "Velocidad de Reservas",
        roc_3m: "ROC 3M",
        spread_zscore: "Z-Score Spread",
        momentum: "Momentum",
        lcr: "LCR",
        reserves_high_stress: "Alto Estrés",
        reserves_normal: "Normal",
        reserves_low_stress: "Bajo Estrés",
        reserves_bullish: "Alcista",
        reserves_bearish: "Bajista",
        reserves_neutral: "Neutral",
        // US System Metrics
        liquidity_score: "Índice de Liquidez",
        rrp_drain: "Drenaje RRP",
        weeks_to_empty: "Semanas hasta vacío",
        tga_deviation: "Desviación TGA",
        fed_momentum_label: "Momentum Fed",
        netliq_roc: "ROC Liq Neta",
        liquid_env: "Líquido",
        dry_env: "Seco",
        regime_qe: "Modo QE",
        regime_qt: "Modo QT",
        // Flow/Impulse Metrics
        flow_impulse: "Impulso de Liquidez",
        flow_accel: "Aceleración",
        flow_zscore: "Z-Score del Impulso",
        flow_desc: "El impulso rastrea la tasa de cambio en los flujos. La aceleración captura cambios de régimen.",
        gli_impulse: "Impulso GLI (13S)",
        m2_impulse: "Impulso M2 (13S)",
        cb_contribution: "Contribución CB a ΔGLI",
        // Formatting
        spot_usd: "Spot USD",
        const_fx: "FX Const",
        // BTC Analysis tab
        btc_analysis_title: "Modelo de Valor Justo de BTC",
        btc_analysis_desc: "Valor justo de Bitcoin derivado de liquidez global, M2 y condiciones de crédito. Precio arriba = sobrevalorado, abajo = infravalorado.",
        current_valuation: "Valoración Actual",
        btc_price: "Precio BTC",
        fair_value: "Valor Justo",
        deviation: "Desviación",
        zscore: "Z-Score",
        lag_analysis: "Señales Predictivas: CLI → BTC Análisis de Retardo",
        roc_window: "Ventana ROC",
        optimal_lag: "Retardo Óptimo",
        max_correlation: "Correlación Máxima",
        interpretation: "Interpretación",
        // BTC Quant v2 tab
        quant_v2_title: "Quant v2: Modelo Mejorado de Valor Justo de Bitcoin",
        quant_v2_desc: "Este modelo aborda problemas econométricos del modelo anterior:",
        quant_v2_weekly: "Frecuencia semanal (W-VIE) en lugar de diaria para evitar autocorrelación",
        quant_v2_log: "Retornos Δlog(BTC) en lugar de niveles log (evita regresión espuria)",
        quant_v2_elastic: "ElasticNet con retardos de 1-8 semanas para selección automática",
        quant_v2_pca: "Factor PCA GLI en lugar de suma cruda (maneja colinealidad)",
        quant_v2_vol: "Volatilidad rolling de 52 semanas para bandas adaptativas",
        oos_metrics: "Métricas Fuera de Muestra",
        model_params: "Parámetros del Modelo",
        quant_chart_desc: "La deriva acumulativa del modelo puede causar divergencia con el tiempo.",
        interp_regression: "Regresión usando:",
        interp_gli_lag: "GLI (retardo 45d)",
        interp_cli_lag: "CLI (retardo 14d)",
        interp_vix_coin: "VIX (coincidente)",
        interp_netliq_lag: "Liq Neta EE.UU. (retardo 30d)",
        interp_zones: "Zonas de Desviación",
        interp_extreme: "±2σ: Sobre/infravaloración extrema",
        interp_moderate: "±1σ: Desviación moderada",
        interp_fair_range: "Dentro de ±1σ: Rango de valor justo",
        interp_signals: "Señales de Trading",
        interp_profittaking: "Z > +2: Considerar toma de beneficios",
        interp_accumulation: "Z < -2: Acumulación potencial",
        interp_divergence: "Divergencia ROC: Cambios de momentum",
        // Data Health & Pulse
        data_health: "Salud de Datos",
        series: "Series",
        real_date: "Fecha Real",
        coverage: "Cobertura",
        active_cbs: "Bancos Activos",
        impulse_analysis: "Análisis de Impulso de Liquidez",
        chart_impulse_desc: "Comparación del momentum de GLI, Liquidez Neta y condiciones de Crédito (Z-Scores Normalizados). Las divergencias suelen liderar el precio de BTC.",
        btc_roc_overlay: "Superposición ROC BTC",
        period: "Periodo",
        lag_days: "Retardo (Días)",
        // Macro Regimes
        regime_bullish: "Macro Alcista",
        regime_bearish: "Macro Bajista",
        regime_global_inj: "Inyección Global",
        regime_us_inj: "Inyección EE.UU.",
        regime_early_warning: "Aviso Temprano",
        regime_losing_steam: "Perdiendo Fuelle",
        regime_neutral: "Neutral / Transición",
        regime_signal: "Pulso Macro y Régimen",
        regime_chart_desc: "Precio BTC (Log) vs Régimen Macro. El fondo rastrea liquidez Global (GLI) y EE.UU. (NetLiq). Verde: Expansión Dual (Alcista). Rojo: Contracción Dual (Bajista). Gris: Neutral.",
        regime_formula_title: "Fórmula del Régimen",
        percentile: "Percentil",
        regime_formula_desc: "Score = 50 + 15 × Total_Z | Liquidez (35% GLI + 35% NetLiq + 20% M2 ± amplitud CB) + Crédito (60% CLI + 40% momentum CLI) - Frenos (tasas reales + estrés repo + escasez reservas)",
        regime_score_bullish: "Score > 50: Sesgo alcista (verde) → Liquidez expandiéndose, crédito relajándose",
        regime_score_bearish: "Score < 50: Sesgo bajista (rojo) → Liquidez contrayéndose, crédito endureciéndose",
        // Risk Model Tab
        risk_stance: "SESGO",
        risk_factors: "Factores",
        risk_bullish: "Alcista",
        risk_bearish: "Bajista",
        status_bullish: "ALCISTA",
        status_bearish: "BAJISTA",
        status_neutral: "NEUTRAL",
        status_warning: "AVISO",
        status_ok: "OK",
        status_stress: "ESTRÉS",
        tips_breakeven: "Breakeven",
        tips_real_rate: "Tasa Real",
        tips_fwd: "Forward 5Y5Y",
        tips_be_desc: "Expectativas inflación",
        tips_rr_desc: "Coste del dinero",
        tips_fwd_desc: "Anclaje largo plazo",
        tips_signal_label: "Señal Macro TIPS",
        cli_stance: "SESGO CLI",
        cli_top_30: "Top 30%",
        cli_bottom_30: "Bottom 30%",
        cli_mid_range: "Rango medio",
        cli_desc_ext: "↑ CLI = Crédito fácil (alcista) ↓ Contracción = Más estricto (bajista)",
        repo_rate: "Tasa",
        repo_value: "Valor",
        repo_spread_sig: "Spread/Señal",
        credit_hy_name: "Contraste Spread HY",
        credit_hy_desc: "Spread High Yield vs Treasury. Mayor = Risk-off, Menor = Risk-on.",
        credit_ig_name: "Contraste Spread IG",
        credit_ig_desc: "Spreads Grado Inversión. Mayor = Estrés, Menor = Sólido.",
        credit_nfci_credit_name: "Crédito (NFCI)",
        credit_nfci_credit_desc: "Índice de Condiciones Financieras Fed Chicago (Sub-crédito).",
        credit_nfci_risk_name: "Riesgo (NFCI)",
        credit_nfci_risk_desc: "Índice de Condiciones Financieras Fed Chicago (Sub-riesgo).",
        credit_lending_name: "Préstamos (SLOOS)",
        credit_lending_desc: "Encuesta de Opinión de Préstamos. % Neto bancos endureciendo.",
        credit_vix_name: "Volatilidad (VIX)",
        credit_vix_desc: "Índice de Volatilidad CBOE. Mayor = Miedo/Estrés, Menor = Complacencia.",
        indicator_move_name: "Contraste Índice MOVE",
        indicator_move_desc: "Índice ICE BofA MOVE. Mide la volatilidad implícita de los bonos. Alto = Estrés.",
        indicator_fx_vol_name: "Contraste Volatilidad FX",
        indicator_fx_vol_desc: "Volatilidad EuroCurrency de CBOE (EVZ). Mide el estrés del mercado de divisas.",
        signal_status: "Estado Señal",
        roc_title: "Pulso de Momentum (ROC)",
        roc_factor: "Factor",
        indicator_gli: "GLI Global",
        indicator_netliq: "Liquidez Neta EE.UU.",
        indicator_cli: "Crédito (CLI)",
        indicator_real_rates: "Tasas Reales (5Y)",
        indicator_vix: "Volatilidad (VIX)",
        indicator_move: "Índice MOVE (Bonos)",
        indicator_fxvol: "Volatilidad FX (EVZ)",
        indicator_fed: "Activos Fed",
        indicator_ecb: "Activos BCE",
        indicator_boj: "Activos BoJ",
        indicator_boe: "Activos BoE",
        indicator_pboc: "Activos PBoC",
        indicator_boc: "Activos BoC",
        indicator_rba: "Activos RBA",
        indicator_snb: "Activos SNB",
        indicator_bok: "Activos BoK",
        indicator_rbi: "Activos RBI",
        indicator_cbr: "Activos CBR",
        indicator_bcb: "Activos BCB",
        indicator_rbnz: "Activos RBNZ",
        indicator_sr: "Sveriges Riksbank",
        indicator_bnm: "Activos BNM",
        indicator_us_m2: "M2 EE.UU.",
        indicator_eu_m2: "M2 Eurozona",
        indicator_cn_m2: "M2 China",
        indicator_jp_m2: "M2 Japón",
        indicator_uk_m2: "M2 Reino Unido",
        indicator_ca_m2: "M2 Canadá",
        indicator_au_m2: "M2 Australia",
        indicator_in_m2: "M2 India",
        indicator_ch_m2: "M2 Suiza",
        indicator_ru_m2: "M2 Rusia",
        indicator_br_m2: "M2 Brasil",
        indicator_kr_m2: "M2 C. del Sur",
        indicator_mx_m2: "M2 México",
        indicator_my_m2: "M2 Malasia",
        // Signal Reasons - HY Spread
        signal_hy_bullish: "HY spread contraído: apetito por riesgo, crédito fácil.",
        signal_hy_bearish: "HY spread ampliado: aversión al riesgo, estrés crediticio.",
        signal_hy_neutral: "HY spread en rango normal, sin señal extrema.",
        // Signal Reasons - IG Spread
        signal_ig_bullish: "IG spread bajo: condiciones crediticias sólidas.",
        signal_ig_bearish: "IG spread elevado: tensión en mercado de crédito.",
        signal_ig_neutral: "IG spread estable, condiciones normales.",
        // Signal Reasons - NFCI Credit
        signal_nfci_credit_bullish: "NFCI Credit negativo: condiciones crediticias laxas.",
        signal_nfci_credit_bearish: "NFCI Credit positivo: condiciones crediticias restrictivas.",
        signal_nfci_credit_neutral: "NFCI Credit neutral, sin presión extrema.",
        // Signal Reasons - NFCI Risk
        signal_nfci_risk_bullish: "NFCI Risk bajo: riesgo sistémico contenido.",
        signal_nfci_risk_bearish: "NFCI Risk elevado: mayor riesgo sistémico percibido.",
        signal_nfci_risk_neutral: "NFCI Risk en niveles normales.",
        // Signal Reasons - Lending
        signal_lending_bullish: "Estándares de crédito relajados: expansión crediticia.",
        signal_lending_bearish: "Estándares restrictivos: contracción crediticia.",
        signal_lending_neutral: "Estándares de préstamo sin cambio significativo.",
        // Signal Reasons - VIX
        signal_vix_bullish: "VIX bajo: complacencia/confianza en el mercado.",
        signal_vix_bearish: "VIX elevado: miedo y volatilidad en el mercado.",
        signal_vix_neutral: "VIX en rango normal, volatilidad moderada.",
        // Signal Reasons - CLI
        signal_cli_bullish: "CLI indica expansión crediticia y apetito por riesgo.",
        signal_cli_bearish: "CLI indica contracción crediticia y aversión al riesgo.",
        signal_cli_neutral: "CLI neutral, condiciones de liquidez equilibradas.",
        // Signal Reasons - Repo
        signal_repo_bullish: "SOFR ≈ IORB: liquidez interbancaria adecuada.",
        signal_repo_bearish: "SOFR >> IORB: tensión de liquidez en repo.",
        signal_repo_neutral: "Spread repo en rangos normales.",
        signal_repo_warning: "SOFR << IORB: exceso de liquidez (inusual).",
        // Signal Reasons - TIPS
        signal_tips_bullish: "Reflación: BE alto + RR bajo. Fed dovish, expansión económica.",
        signal_tips_bearish: "Tightening: RR alto + BE bajo. Fed hawkish, restricción monetaria.",
        signal_tips_neutral: "Goldilocks: BE y RR en rango normal, equilibrio macro.",
        signal_tips_warning: "Stagflation: Inflación alta + Fed hawkish. Condiciones adversas.",
        signal_tips_disinflation: "Desinflación: BE y RR bajos. Posible desaceleración o deflación.",
        signal_move_bullish: "MOVE bajo: mercado de bonos/liquidez estable.",
        signal_move_bearish: "MOVE alto: estrés en bonos/reevaluación.",
        signal_move_neutral: "MOVE promedio: volatilidad de bonos normal.",
        signal_fx_vol_bullish: "Vol FX baja: flujos globales estables.",
        signal_fx_vol_bearish: "Vol FX alta: estrés en el mercado de divisas.",
        signal_fx_vol_neutral: "Vol FX promedio: volatilidad de divisas normal.",
        // Regimes Tab (Spanish)
        nav_regimes: "Regímenes",
        regimes_header: "Regímenes Macro",
        regimes_header_desc: "Clasificación cuantitativa de regímenes usando indicadores de liquidez, crédito, crecimiento y frenos monetarios.",
        regime_v2a_title: "V2A: Consciente de Inflación",
        regime_v2a_formula: "Score = 50×Liquidez + 25×Crédito + 25×Frenos",
        regime_v2a_desc: "Enfocado en presiones inflacionarias mediante frenos monetarios. Adecuado para entornos de alta inflación.",
        regime_v2b_title: "V2B: Consciente del Crecimiento",
        regime_v2b_formula: "Score = 40×Liquidez + 25×Crédito + 20×Crecimiento + 15×Frenos",
        regime_v2b_desc: "Equilibra el momentum de crecimiento con condiciones crediticias. Mejor para análisis enfocado en crecimiento.",
        regime_bullish_label: "ALCISTA",
        regime_bearish_label: "BAJISTA",
        regime_neutral_label: "NEUTRAL",
        regime_bullish_desc: "Expansión dual: Tanto la liquidez global como la doméstica expandiéndose. Condiciones crediticias relajándose.",
        regime_bearish_desc: "Contracción dual: Tanto la liquidez global como la doméstica contrayéndose. Crédito endureciéndose.",
        regime_neutral_desc: "Régimen mixto/divergente: Señales conflictivas entre condiciones globales y domésticas.",
        regime_current_values: "Valores Actuales",
        regime_liquidity: "Liquidez",
        regime_credit: "Crédito",
        regime_growth: "Crecimiento",
        regime_brakes: "Frenos",
        regime_total_z: "Z Total",
        regime_btc_overlay_v2a: "BTC + Régimen V2A (Consciente de Inflación)",
        regime_btc_overlay_v2b: "BTC + Régimen V2B (Consciente del Crecimiento)",
        regime_btc_desc: "Precio BTC en escala log sobre Régimen Macro. Verde: Expansión Dual (Alcista). Rojo: Contracción Dual (Bajista). Gris: Mixto/Neutral.",
        cli_v1_label: "CLI V1 (Original)",
        cli_v2_label: "CLI V2 (Mejorado)",
        cli_comparison_title: "Comparación CLI V1 vs V2",
        cli_v2_formula: "CLI V2 = HY Spread + HY Momentum + IG Spread + NFCI Crédito/Riesgo + Préstamos + MOVE + Vol FX + Curva Rendimiento + Shock Tasa Real",
        block_decomposition_title: "Descomposición por Bloques del Régimen",
        block_decomp_desc: "Contribución de cada bloque (Liquidez, Crédito, Crecimiento, Frenos) al score total. Normalizado Z-Score.",
        stress_historical_title: "Dashboard de Estrés Histórico",
        stress_historical_desc: "Inflación (7) + Liquidez (7) + Crédito (7) + Volatilidad (6) = 27 máx. Niveles: BAJO (0-4), MODERADO (5-9), ALTO (10-14), CRÍTICO (15+).",
        // Comprehensive Sweep Additions
        // UsSystemTab
        reserves_t: "Reservas Bancarias (T)",
        net_liq_t: "Liquidez Neta (T)",
        reserves_axis: "Reservas (T)",
        net_liq_axis: "Liq Neta (T)",
        reserves_ample: "Amplias ($3.0T)",
        reserves_scarce: "Escasas ($2.5T)",
        reserves_velocity_title: "Velocidad de Reservas",
        signal_qe: "QE",
        signal_qt: "QT",
        // spread_zscore: "Spread Z-Score", // Duplicate
        // reserves_high_stress: "Alto Estrés", // Duplicate
        // reserves_low_stress: "Bajo Estrés", // Duplicate
        // reserves_normal: "Normal", // Duplicate
        // momentum: "Momentum", // Duplicate
        fed_momentum: "Momentum Fed",
        delta_4w_netliq: "Δ4S Liq Neta",
        bullish: "Alcista",
        bearish: "Bajista",
        risk_on: "Risk-ON",
        risk_off: "Risk-OFF",
        env_liquid: "Líquido",
        env_dry: "Seco",
        // netliq_roc: "ROC Liq Neta", // Duplicate
        chart_net_repo_ops: "Operaciones Netas de Repo",
        net_repo_zero: "Cero (Neutral)",
        net_repo_srf_usage: "Uso SRF (Inyección)",
        net_repo_axis: "Repo Neto ($B)",
        srf_usage_axis: "Uso SRF ($B)",
        injection_zone: "Zona de Inyección",
        drain_zone: "Zona de Drenaje",
        metric_header: "Métrica",
        value_header: "Valor",
        signal_header: "Señal",

        // RiskModelTab
        chart_cli_z: "CLI Agregado (Z-Score)",
        chart_cli_pct: "CLI (Percentil)",
        chart_hy_z: "Spread HY (Z-Score)",
        chart_hy_pct: "Spread HY (Percentil)",
        chart_hy_raw: "Spread HY (bps)",
        chart_ig_z: "Spread IG (Z-Score)",
        chart_ig_pct: "Spread IG (Percentil)",
        chart_ig_raw: "Spread IG (bps)",
        // view_raw: "Original", // Duplicate
        // view_zscore: "Z-Score", // Duplicate
        // view_percentile: "Percentil", // Duplicate
        divergence_z_axis: "Divergencia (Z)",
        divergence_pct_axis: "Percentil (%)",
        chart_repo_corridor: "Corredor de Tasas Fed (SOFR vs Bandas)",
        // sofr_iorb_spread: "Spread SOFR-IORB", // Duplicate
        // gap_to_ceiling: "Brecha al Techo", // Duplicate
        status_label: "Estado",
        warning: "ADVERTENCIA",
        tips_be_label: "BE",
        tips_rr_label: "TR",

        // BtcAnalysisTab & BtcQuantV2Tab
        chart_lag_corr: "Correlación de Retardo ROC",
        chart_corr_gli_btc: "GLI vs BTC",
        chart_corr_cli_btc: "CLI vs BTC",
        chart_corr_vix_btc: "VIX vs BTC",
        chart_corr_netliq_btc: "Liq Neta vs BTC",
        chart_cross_corr_title: "Análisis de Correlación Cruzada (Ventana 90D)",
        cross_corr_desc: "Retardo negativo = indicador lidera BTC | Positivo = BTC lidera",
        chart_momentum_comp: "Comparación de Momentum (ROC %)",
        col_asset: "Activo",
        col_1m: "1M",
        col_3m: "3M",
        col_6m: "6M",
        col_1y: "1A",
        label_global_gli: "GLI Global",
        label_us_net_liq: "Liq Neta EE.UU.",
        quant_v2_subtitle: "Retornos semanales Δlog + ElasticNet + Factor GLI PCA",
        metric_rmse: "OOS RMSE",
        metric_mae: "OOS MAE",
        metric_hit_rate: "Tasa de Acierto",
        metric_r2: "R² Muestra",
        metric_alpha: "Alpha (λ)",
        metric_l1_ratio: "Ratio L1",
        metric_freq: "Frecuencia",
        metric_features: "Características",
        active_features: "Características Activas",
        chart_quant_v2_cum: "Bitcoin: Quant v2 Valor Justo (Semanal - Acumulado)",
        quant_v2_drift_warn: "La deriva acumulativa puede causar divergencia con el tiempo",
        chart_quant_v2_rebal: "Bitcoin: Valor Justo Rebalanceado (Reinicio Trimestral)",
        quant_v2_reset_note: "Se reinicia al precio real cada 13 semanas para evitar deriva",
        chart_returns_comp: "Retornos Semanales: Predicho vs Real (%)",
        returns_comp_legend: "Barras naranja = Real | Línea verde = Predicho",

        // RiskModelTab Supplement
        chart_treasury_10y: "Rendimiento UST 10A (%)",
        chart_treasury_10y_z: "Rendimiento 10A (Z-Score)",
        chart_treasury_10y_pct: "Rendimiento 10A (Percentil)",
        chart_treasury_2y: "Rendimiento UST 2A (%)",
        chart_treasury_2y_z: "Rendimiento 2A (Z-Score)",
        chart_treasury_2y_pct: "Rendimiento 2A (Percentil)",
        chart_treasury_30y: "Rendimiento UST 30A (%)",
        chart_treasury_30y_z: "Rendimiento 30A (Z-Score)",
        chart_treasury_30y_pct: "Rendimiento 30A (Percentil)",
        chart_yield_curve_z: "Curva de Rendimiento (Z-Score)",
        chart_stlfsi4_raw: "STLFSI4 (Original)",
        chart_kcfsi_raw: "KCFSI (Original)",
        repo_srf_ceiling: "Tasa SRF (Techo)",
        repo_iorb_floor: "IORB (Piso)",
        legend_1y: "1A",
        legend_2y: "2A",
        legend_5y: "5A",
        legend_10y: "10A",
        chart_inflation_exp_1y: "Exp. Inflación 1A (%)",
        chart_inflation_exp_2y: "Exp. Inflación 2A (%)",
        chart_inflation_exp_5y: "Exp. Inflación 5A (%)",
        chart_inflation_exp_10y: "Exp. Inflación 10A (%)",
        chart_nfci_credit: "Crédito NFCI",
        chart_nfci_risk: "Riesgo NFCI",
        spread_1y_2y: "Diferencial (1A-2A)",

        // BtcAnalysisTab Supplements
        model_macro: "Liquidez Macro",
        model_adoption: "Macro + Adopción",
        window_7d: "7 Días",
        window_14d: "14 Días",
        window_30d: "30 Días",
        freq_weekly: "Semanal",

        // RegimesTab Supplements
        // stress_critical: "CRÍTICO", // Duplicate
        // stress_high: "ALTO", // Duplicate
        // stress_moderate: "MODERADO", // Duplicate
        // stress_low: "BAJO", // Duplicate
        stress_inflation: "Inflación",
        stress_liquidity: "Liquidez",
        stress_credit: "Crédito",
        // stress_volatility: "Volatilidad", // Duplicate
        stress_score_y: "Puntaje de Estrés",
        regime_score_label: "PUNTAJE",
        best_offset_label: "Mejor Desfase",
        calculate_label: "Calcular",
        offset_days_label: "Desfase (Días):",
        regime_v2a_score_title: "Puntaje Régimen Macro V2A",
        regime_v2b_score_title: "Puntaje Régimen Macro V2B",

        // Dashboard2 Supplements
        rrp_buffer: "Buffer RRP",
        no_major_settlements: "Sin liquidaciones importantes próx. 7d",
        stress_panel_title: "Dashboard de Estrés de Mercado",
        risk_on_label: "RISK-ON",
        risk_off_label: "RISK-OFF",
        neutral_label: "NEUTRAL",
        supportive_factors: "FACTORES DE APOYO",
        loading_analysis: "Cargando análisis...",
        loading: "Cargando...",
        no_data: "Sin datos",
        stress_global: "Nivel de Estrés Global",

        // UsSystemTab Risk Assessment
        overall_risk_level: "Nivel de Riesgo General",
        risk_level_critical: "CRÍTICO",
        risk_level_moderate: "MODERADO",
        risk_level_caution: "PRECAUCIÓN",
        risk_level_low: "BAJO",
        risk_summary_critical: "Alto riesgo de crisis de financiamiento. Intervención de la Fed probablemente necesaria.",
        risk_summary_moderate: "Estrés en evolución detectado. Monitorear desacople de tasas y uso del SRF.",
        risk_summary_caution: "Buffer de liquidez estrechándose. Vigilar agotamiento del RRP.",
        risk_summary_low: "Liquidez adecuada. Sistema funcionando correctamente.",
        risk_reserves_critical: "Reservas Críticamente Escasas (<$2.5T)",
        risk_reserves_low: "Reservas acercándose al piso de confort (<$2.8T)",
        risk_sofr_stress: "Estrés severo de financiamiento (SOFR >> IORB)",
        risk_sofr_decoupling: "Desacople de tasa de mercado del piso de la Fed",
        risk_srf_active: "Uso Activo del SRF",

        // UsSystemTab Regime Labels
        regime_injection: "INYECCIÓN",
        regime_heavy_drain: "DRENAJE PESADO",
        regime_drain: "DRENAJE",

        // UsSystemTab Repo Panel
        net_pos_label: "Posición Neta",
        regime_label: "Régimen",
        srf_inject_label: "SRF (Inyecta)",
        rrp_drain_label: "RRP (Drena)",
        net_repo_operations: "Operaciones Netas de Repo",
        net_repo_desc: "Neto = Uso SRF (inyección) - Uso RRP (drenaje). Positivo = Fed añade liquidez. Negativo = Fed retira liquidez.",

        // UsSystemTab SOFR Corridor
        sofr_corridor_desc: "SOFR debería operar entre IORB (piso) y Tasa SRF (techo). Acercarse al techo o uso del SRF señala estrés de financiamiento.",
        sofr_volume_desc: "El volumen de transacciones SOFR mide la profundidad del mercado repo. Volumen cayendo = señal temprana de disfunción.",

        // RiskModelTab Treasury Yields
        treasury_10y_desc: "Rendimiento del Tesoro a 10 años de vencimiento constante. Tasa de referencia clave.",
        treasury_2y_desc: "Rendimiento del Tesoro a 2 años de vencimiento constante. Tasa de corto plazo.",
        yield_curve_30y10y_desc: "Pendiente de la curva de largo plazo. Inversión = estrés severo.",

        // UsDebtTab - Treasury Maturity Tracker
        us_debt_tab: "Deuda EE.UU.",
        treasury_maturity_tracker: "Rastreador de Vencimientos del Tesoro",
        demo_data: "DATOS DEMO",
        peak_maturity_month: "Mes Pico de Vencimiento",
        highest_refinancing: "Mayor refinanciamiento",
        peak_amount: "Monto Pico",
        single_month_max: "Máximo de un solo mes",
        bills_outstanding: "Letras Pendientes",
        short_term_debt: "Deuda a corto plazo",
        total_outstanding: "Total Pendiente",
        marketable_debt: "Deuda negociable",
        next_12m_refinancing: "Refinanciamiento Próx. 12M",
        must_be_rolled: "Debe ser renovado",
        forecast_horizon: "Horizonte de Pronóstico",
        months_abbr: "Me",
        projection_period: "Período de proyección",
        maturity_schedule_title: "Calendario de Vencimientos por Tipo",
        stacked: "Apilado",
        line: "Línea",
        monthly_maturity_schedule: "Calendario Mensual de Vencimientos ($ Miles de Millones)",
        updated: "Actualizado",
        treasury_bills: "Letras del Tesoro",
        treasury_notes: "Notas del Tesoro",
        treasury_bonds: "Bonos del Tesoro",
        amount_billions: "Monto ($ Miles de Millones)",
        loading_treasury_data: "Cargando datos del tesoro...",
        source: "Fuente",
        total: "Total",
        month: "Mes",
    },
};

// Derived store for current translations based on language
export const currentTranslations = derived(language, ($lang) => translations[$lang] || translations.en);

/**
 * Translation helper function.
 * Use with $currentTranslations in components.
 * @param {object} trans - The $currentTranslations store value
 * @param {string} key - Translation key
 * @returns {string}
 */
export const t = (trans, key) => trans[key] || translations.en[key] || key;

// Theme management functions
export function initSettings() {
    if (typeof localStorage !== 'undefined') {
        const savedTheme = localStorage.getItem('theme');
        const savedLang = localStorage.getItem('language');

        darkMode.set(savedTheme === 'dark');
        language.set(savedLang || 'en');
        applyTheme(savedTheme === 'dark');
    }
}

export function toggleDarkMode() {
    darkMode.update(current => {
        const newValue = !current;
        if (typeof localStorage !== 'undefined') {
            localStorage.setItem('theme', newValue ? 'dark' : 'light');
        }
        applyTheme(newValue);
        return newValue;
    });
}

export function toggleLanguage() {
    language.update(current => {
        const newLang = current === 'en' ? 'es' : 'en';
        if (typeof localStorage !== 'undefined') {
            localStorage.setItem('language', newLang);
        }
        return newLang;
    });
}

function applyTheme(isDark) {
    if (typeof document !== 'undefined') {
        document.documentElement.setAttribute('data-theme', isDark ? 'dark' : 'light');
    }
}
